use_frameworks!

platform :ios, '8.0'

target 'JMProject_Example' do
  pod 'JMProject', :path => '../'

  target 'JMProject_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
